### ISSUE TITLE
About Powershell Crashes (on wget)

### ISSUE THREAD

**Issue by ghost** [CoolMan119/EasyPrompt#1]
The reason behind it is missing permissions (which will happen on most computers) for running external scripts. Here is something you could put in your readme for others who run into the same issue (just to make life easier).

## Why does wget downloader crash?
wget-downloader will crash if your system does not allow powershell scripts to run.
Open Windows PowerShell ISE as an administrator, and type the following into the shell: `Set-ExecutionPolicy RemoteSigned`

**Comment by CoolMan119** [comment]
Added, Thanks.

**Comment by CoolMan119** [comment]
Added, Thanks.
